<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Pop.Plugin.Logging\src\Pop.Plugins.Logging.csproj" />
    <ProjectReference Include="..\..\Pop.Plugins.Abstractions\src\Pop.Plugins.Abstractions.csproj" />
  </ItemGroup>

</Project>
